---

- name: Elasticsearch with opendistro configuration
  hosts: es-cluster
  gather_facts: false
  environment: 
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  roles:
    - { role: centos7/elasticsearch_opendistro }
