---
# tasks file for elasti- name: include java.yml
- hostname:
    name: "{{ inventory_hostname }}"

- name: Populate the nodes to /etc/hosts
  import_tasks: etchosts.yml

- name: include java.yml
  include: java.yml
  when: es_java_install

- name: include elasticsearch installation
  include: elasticsearch.yml

- name: include opendistro security for elasticsearch
  include: opendistro_security.yml
  when: opendistro_security_install

- name: include opendistro alerting for elasticsearch
  include: opendistro_alerting.yml
  when: opendistro_alerting_install

- name: include opendistro sql for elasticsearch
  include: opendistro_sql.yml
  when: opendistro_sql_install

- name: include opendistro job scheduler for elasticsearch
  include: opendistro_job_scheduler.yml
  when: opendistro_job_scheduler_install

- name: include opendistro perfomance analyzer for elasticsearch
  include: opendistro_performance_analyzer.yml
  when: opendistro_performance_analyzer_install

- name: include opendistro index management for elasticsearch
  include: opendistro_index_management.yml
  when: opendistro_index_management_install

- name: include kibana installation
  include: kibana.yml
  when: inventory_hostname in groups['kibana']

- name: include opendistro security for kibana
  include: opendistro_security_kibana.yml
  when: opendistro_security_install_kibana and inventory_hostname in groups['kibana']

- name: Wait for elasticsearch to startup
  wait_for: host={{ hostvars[inventory_hostname]['ip'] }} port={{es_api_port}} delay=5 connect_timeout=1
