---

- name: SQL Plugin Install | Download Opendistro Elasticsearch SQL plugin {{ opendistro_sql_version }}
  get_url:
    url: "{{ opendistro_sql_download_url }}opendistro_sql-{{ opendistro_sql_version }}.zip"
    dest: "{{ es_home }}/opendistro_sql-{{ opendistro_sql_version }}.zip"
  register: download

- name: SQL Plugin Install | Install the Opendistro SQL plugin
  command: "{{ es_plugin_bin_path }} install -b file://{{ es_home }}/opendistro_sql-{{ opendistro_sql_version }}.zip"
  when: download.changed
  register: install

- name: SQL Plugin Install | Restart elasticsearch with SQL configuration
  systemd:
    name: elasticsearch
    state: restarted
  when: install.changed

- name: Wait for port 9300 to become open on the hosts
  wait_for:
    host: "{{ ansible_host }}"
    port: 9300
    delay: 20
  when: install.changed


